id = "purelint"
name = "Purelint"
version = "0.0.1"
schema_version = 1
authors = ["Mark"]
description = "PureScript linter inspired by hlint"

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.purelint]
language = "PureScript"
